[General]
Background="/var/cache/niri-rice/wallpaper"
MainColor={{colors.on_surface.default.hex}}
AccentColor={{colors.primary.default.hex}}
BackgroundColor={{colors.surface.default.hex}}
OverrideTextFieldColor={{colors.on_surface.default.hex}}
placeholderColor={{colors.on_surface_variant.default.hex}}
IconColor={{colors.on_surface.default.hex}}
