[General]
Background="/var/cache/niri-rice/wallpaper"
MainColor={{colors.on_surface.default.hex}}
AccentColor={{colors.primary.default.hex}}
BackgroundColor={{colors.surface.default.hex}}
HourFormat="hh:mm AP"
